/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import proyectointegrado.dao.DAOdepartamento;
import proyectointegrado.dao.Departamento;
import proyectointegrado.dao.FactoryDAO;

/**
 *
 * @author Luis Alberto
 */
public class TablaDepartamento extends javax.swing.JInternalFrame {
     
    private static TablaDepartamento tablDep = null;
    private DAOdepartamento daoDep = (DAOdepartamento) FactoryDAO.create(FactoryDAO.TypeDAO.DEPARTAMENTO);
    private Departamento dep = new Departamento();
    private  DefaultTableModel modelo;

    public static TablaDepartamento getInstace() {
        if (tablDep == null) {
            tablDep = new TablaDepartamento();
            return tablDep;
        }
        return tablDep;
    }
    
    
    /**
     * Creates new form TablaDepartamento
     */
    public TablaDepartamento() {
        initComponents();
        modelo = (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MostrarUno = new javax.swing.JMenuItem();
        MostrarTodos = new javax.swing.JMenuItem();

        setClosable(true);
        setTitle("Tabla de Departamentos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jMenu1.setText("Mostar");

        MostrarUno.setText("Mostrar Uno");
        MostrarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarUnoActionPerformed(evt);
            }
        });
        jMenu1.add(MostrarUno);

        MostrarTodos.setText("Mostrar Todos");
        MostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTodosActionPerformed(evt);
            }
        });
        jMenu1.add(MostrarTodos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTodosActionPerformed
        // TODO add your handling code here:
        daoDep.MostrarTodos(dep,modelo);
    }//GEN-LAST:event_MostrarTodosActionPerformed

    private void MostrarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarUnoActionPerformed
        // TODO add your handling code here:
        dep.setClave(JOptionPane.showInputDialog("Ingrese la Clave"));
        daoDep.MostrarUno(dep,modelo);
    }//GEN-LAST:event_MostrarUnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MostrarTodos;
    private javax.swing.JMenuItem MostrarUno;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
